stages:
  - install
  - test
  - deploy

install:
  stage: install
  script:
    - pip install .

test:
  stage: test
  script:
    - pip install pytest
    - pytest

deploy:
  script:
    - python setup.py sdist bdist_wheel
