stages:
  - install
  - test
  - deploy

install:
  stage: install
  script:
    - pip install .

test:
  stage: test
  script:
    - pip install .
    - pip install pytest
    - pytest

coverage:
  stage: test
  script:
    - coverage run --source=sap -m pytest
    - coverage report -m

deploy:
  stage: deploy
  script:
    - python setup.py sdist bdist_wheel
  only:
    - master
