stages:
  - install
  - test
  - deploy

install:
  stage: install
  script:
    - pip install .

test:
  stage: test
  script:
    - pip install .
    - pip install pytest
    - pytest

coverage:
  stage: test
  script:
    - pip install .
    - pip install coverage pytest
    - coverage run --source=sap -m pytest
    - coverage report -m
  coverage: /\d+\%\s*$/

deploy:
  stage: deploy
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine -u $RUSER -p $RPASS upload dist/*
  only:
    - master
    - twine
