image: python:3.7

stages:
  - install
  - quality
  - deploy

install:
  stage: install
  script:
    - pip install .

test:
  stage: quality
  script:
    - pip install .
    - pip install pytest
    - pytest

coverage:
  stage: quality
  script:
    - pip install .
    - pip install coverage pytest
    - coverage run --source=sap -m pytest
    - coverage report -m
  coverage: /\d+\%\s*$/

doc:
  stage: quality
  script:
    - echo paper please

deploy:
  stage: deploy
  script:
   #- pip install twine
    - python setup.py sdist bdist_wheel
   #- twine upload -u $RUSER -p $RPASS dist/*
    - echo curl -X POST "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/tags" --header "PRIVATE-TOKEN:${TOKEN}" --data "tag_name=$(python setup.py --version)&ref=${CI_COMMIT_REF_NAME}"
    - curl -X POST "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/tags" --header "PRIVATE-TOKEN:${TOKEN}" --data "tag_name=$(python setup.py --version)&ref=${CI_COMMIT_REF_NAME}"
    #- "curl -X POST -F token=$TOKEN -F ref=$CI_COMMIT_REF_NAME -F tag_name=v$(python setup.py --version) https://gitlab.inria.fr/api/v4/projects/17072/repository/tags"
  only:
    - master
    - twine
